name: LFormer  # project_name
dataset_name: 'cave_x4'  # only support 'GF2', 'WV3', 'WV2', 'cave'
model_name: 'LFormer'
# train setting
alpha: 0.1
epoch_num: 500
batch_size: 32
base_lr: 1e-3
weight_decay: 1e-6
# parameters for scheduler lr
gamma: 0.1
step_size: 250
# model setting
pan_dim: 3
lms_dim: 31
attn_dim: 64
hp_dim: 64
n_stage: 5
crop_batch_size: 64
patch_size_list: [16, 64, 64]
scale: 4
patch_merge: True


data_path: 'E:/HJM_Datasets/HISR/cave/x4/train_cave(with_up)x4_rgb.h5'
log_dir: './logs'
# tensorboard file path
tb_log_path: './tb_logs'
weights_path: './weights/'
results_path: './results/'
gpu_list: [0]
workers: 0
save_epoch: 25

test_mode: 'reduced'
test_data_path: '/home/LJL/Proj/pansharpening_data/cave_x4/test_cave_x4_rgb.h5'
test_weight_path: './weights/lformer_R_cave_x4.pth'